### ISSUE TITLE
Prepare bootnodes for testnet3

### ISSUE THREAD

**Issue by ericlee42** [GOATNetwork/genesis-ceremony#1]
# Steps to create a boot node key

## Spin up an AWS ec2 and associate an EIP for it

You can choose x86 or arm instances for it, **16G RAM is required**, e.g. m5.xlarge, m7g.xlarge and m8g.xlarge

## Installation

1. Install docker
2. Mount an EBS to /data
3. Update security groups

| Port  | Description         | Protocol | Source    |
| ----- | ------------------- | -------- | --------- |
| 30303 | goat-geth P2P | UDP      | 0.0.0.0/0 |
| 30303 | goat-geth p2p | TCP      | 0.0.0.0/0 |
| 26656 | goat p2p Port  | TCP      | 0.0.0.0/0 |

## Create p2p key for goat-geth

```console
$ docker run --rm -v /data/geth/geth:/geth -w /geth ethereum/client-go:alltools-latest  bootnode -genkey nodekey -writeaddress
b5a5c0b2052b35a1802345b1ab31c1b24f8c33f647aeb4cab701259d41f723a61a9998099e07a233c1f80d278f0ce66542405fa1596a5cfc8e1a1a763acc70f3
```

the `baa...0f3` is your node public key

## Create p2p key for goat

Get the node pubkey

```console
$ docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:testnet-2 comet show-node-id
dcc947cf646aa3b937fa27e3e1f7647c17109e96
```

the `dcc...96` is your node public key

**Comment by ericlee42** [comment]
MetisDAO

IP: `3.222.213.223`

goat: `997f925d3d4947483c9339ec2765ed8c825ace32`

geth: `ea55fed4d513969ec6048d089d108b12c75610fa808416d7b7a3b1e443113effc7b473f03396be2bfd238b2abef47b454e2da8c8f4da49f7dbd49470efc3efa1`

**Comment by eigmax** [comment]
ZKM
54.68.179.184

goat:  9106b59e244eb8bf4dbedcd03b56e30790278765

Geth: 25fde2ca58a45a561a52b3cae2b0e56b1838f149ba5f7af88e4dc6f76a2647c0f7dd383cc21e744d72bf27f6db9e2ce61eb412e3e9cf9401b8a5be57ec6e4952

**Comment by aiden069** [comment]
Goat Network

IP: 52.32.82.160

goat: c99c2abe0886a3c82c12f611477ce22fe178186a

geth: a7106c2ddce59458bc25cff89812b464db1cd5ca8db6d2045326d60f4b918bb6f74e192ed36e108f4821a499066c06abd51b4905350fa2dc87634286a5872102
