### ISSUE TITLE
Prepare bootnodes for mainnet

### ISSUE THREAD

**Issue by anvztor** [GOATNetwork/genesis-ceremony#4]
# Steps to create a boot node key

## Spin up an AWS ec2 and associate an EIP for it
You can choose x86 or arm instances for it, 16G RAM is required, e.g. m5.xlarge, m7g.xlarge and m8g.xlarge

## Installation
1. Install docker
2. Mount an EBS to /data
3. Update security groups

Port | Description | Protocol | Source
-- | -- | -- | --
30303 | goat-geth P2P | UDP | 0.0.0.0/0
30303 | goat-geth p2p | TCP | 0.0.0.0/0
26656 | goat p2p Port | TCP | 0.0.0.0/0

## Create p2p key for goat-geth
```
$ docker run --rm -v /data/geth/geth:/geth -w /geth ethereum/client-go:alltools-stable bootnode -genkey nodekey -writeaddress
b5a5c0b2052b35a1802345b1ab31c1b24f8c33f647aeb4cab701259d41f723a61a9998099e07a233c1f80d278f0ce66542405fa1596a5cfc8e1a1a763acc70f3
```

the `baa...0f3` your node public key
Create p2p key for goat

## Get the node pubkey
```
$ docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 comet show-node-id
dcc947cf646aa3b937fa27e3e1f7647c17109e96
```
the `dcc...96` is your node public key

## Bootnode precheck
```
docker run --rm -v /data/geth/geth:/geth -w /geth ethereum/client-go:alltools-stable bootnode -nodekey nodekey -writeaddress
docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 comet show-node-id
curl checkip.amazonaws.com
```

**Comment by eigmax** [comment]
ZKM 

3.16.248.103

node pubkey: 84b041c3800b67319d378fbb8d2f83e2c686e738

geth p2p key: 410e728998d3dfcfc864a40bbc7cd15fdc8f8f32e12bd6ce735b26c6454004fa871077a695d0433d235cb09cb82b9d10e9a81dbf82bfeed266fd454a1b36267e

**Comment by bossyuansu** [comment]
6b013c7e07430ff060fa6b570daa556fbf00cb58
8411fdcbadc4ef56e99d937e6549e81fc665fa7dcf89b27936444ed3d8f866b0a48916a4f63dfedc0c51cb2f0ea6799b8eccea5d0914d27b0b214efe937a4812
18.222.86.233

**Comment by EricWGoat** [comment]
GOAT

18.220.78.155

```
GOAT: 445da2a86ee97f08154464fab98d90a3fef08a8f
Geth: 60eba0b2b9dbadb9f40a012f251e68314620b6276ca7877962d46b757956ed864c7b1a0fb11a4b430a6e392385763c8b31b294ecee6f7b44adf6a83a5148483d


```

**Comment by bossyuansu** [comment]
```
ubuntu@ip-12-0-8-190:~$ docker run --rm -v /data/geth/geth:/geth -w /geth ethereum/client-go:alltools-stable bootnode -nodekey nodekey -writeaddress
8411fdcbadc4ef56e99d937e6549e81fc665fa7dcf89b27936444ed3d8f866b0a48916a4f63dfedc0c51cb2f0ea6799b8eccea5d0914d27b0b214efe937a4812
ubuntu@ip-12-0-8-190:~$ docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 comet show-node-id
6b013c7e07430ff060fa6b570daa556fbf00cb58
ubuntu@ip-12-0-8-190:~$ curl checkip.amazonaws.com
18.222.86.233
```

**Comment by bossyuansu** [comment]
4a66e02862566a770b6e5b5f1f87f2acecf48b1af1755874212ea7a1d96a8dfef1c9c9ec40984f5fc349cb1f165ddb3076f4aa8f519cc5e22ec09d935c5124ed
f96b6429528bf55c57b9ba37790233c2ffefb4e8
3.147.156.156
