### ISSUE TITLE
Prepare validators for mainnet

### ISSUE THREAD

**Issue by anvztor** [GOATNetwork/genesis-ceremony#5]
# Steps to create a genesis validator

## Spin up an AWS ec2 and associate an EIP for it
You can choose x86 or arm instances for it, e.g. c5.2xlarge, c7g.2xlarge and c8g.2xlarge

You should make sure that it can access the public internet.

## Installation
1. Install docker
2. Mount an EBS to /data
3. Update security groups

Port | Description | Protocol | Source
-- | -- | -- | --
30303 | goat-geth P2P | UDP | 0.0.0.0/0
30303 | goat-geth p2p | TCP | 0.0.0.0/0
26656 | goat p2p Port | TCP | 0.0.0.0/0

## Create validator private key and get the creation proof
```
$ docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 modgen locking sign --owner 0x...abc --eth-chain-id 2345
{
 "owner": "0x246b2a34aa4d27bf5a90e3f91e733d8b942c10c2",
 "pubkey": "0x22978cffa038a1e489eb186934df5593b980592abc96f07371315b749125ca5772555d6f0fd7a4933d50b0276c6adf8c90fa899baef4036e88e0a8d0aac1f10b",
 "signature": "0x2f466482af1bc206f616778d29d2c33b7037bd1302e4195dd3bf2d184d9bd4064c12b684fe134ab761c7f68dba3f216a378e2e3b9512c0c9fc651605e989c77900",
 "validator": "0x75c54dfb361dcb23faa0db6e23445cb097ca92a7"
}
```
replace the 0x...abc, that is your validator owner eth address

## Deposit
```
docker run --rm ghcr.io/goatnetwork/goat:v0.1.1 modgen bitcoin deposit-address \
--eth-address 0x..ownerAddress... --network mainnet \
--pubkey 03ce99e6a250a720251c05a021019f894cf639f653d51e9b05e3cfc04c88ee9b5d  
```
You will get the deposit address for your validator, and you need to deposit 1 BTC to the address.
```
deposit address bc1...k7f
```
## Comment
Put the json output and your deposit transaction here

## Validator precheck
```
docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 modgen locking sign --owner 0x_owner_address --eth-chain-id 2345
```

**Comment by eigmax** [comment]
ZKM

```
{
 "owner": "0xa3ae64125631f56b1b96b113a79545f4684e67bb",
 "pubkey": "0x7884e3b1702ab2c6eaa014d19df08a0fa290d6eefa14534c3c52a17a5f04040e5ac72a39fdc932f284aab0a21677df3820d9af904e608f191d6fd745994c27d1",
 "signature": "0x8926a8980165f476df319c0495edeae7e5a425e6b9d21a10245f5e68a588abe8673e8fdf0282612c2c0b204ca84710076ac37616e4e01875e821639cb4d4be7000",
 "validator": "0x57e4aa9111e3899547d51d8f1510878f4a1fe2d6"
}
```

deposit address bc1q2k7gwlgkdz4rhhmrfk6lj5shqpvaugas2arf8wjkprth75jucy6s7zdk7f

**Comment by EricWGoat** [comment]
GOAT
```
{
 "owner": "0x32444c83c841146a92ad936cdd93b93b9898f6b9",
 "pubkey": "0xd8ef2fcd6eb3c9c1afdbaadd387417f945047139410b5ebef2c69d2f9acfddbb4215e9f5323e221c4cb45728ae3623c0d8ca51af33c1550d4511ca5dfba0d8e9",
 "signature": "0x6c03b38137361f09e3cecc3981ef47eafd8e63d83159924a989a9c3087fb05d144b5179a56897d1dd6a23ea5b06b9a6664212befc3639ab4f392106d8027f81b01",
 "validator": "0xa075e25ad183e70abd35639d8a9df57889a9d733"
}

deposit address bc1q8vwmf9lvwkzqwsk5t5leuzq66fxg9sa7zs5uaktzmky9vk3gjw5svk7xcp
```

**Comment by bossyuansu** [comment]
{
 "owner": "0x09ccd1cb6be49c131c0dd636c95b4e4f5bc549ad",
 "pubkey": "0xeb0881378a4a61f4d27c99460fe4fdf57f9f12423913f037b97f154f481079ada6edaba9d9f219969f5eefdf7af598322f841ad6bb4a1fd85924f32701facb45",
 "signature": "0x350d5782a5df5af8371b5157c4230fcb16afe2edbf775f2634700216eaa72f0e51d458706feb0639519d6556a9ba2e741bc6a03dbb1a50aa71f024ebcff3ea5201",
 "validator": "0x3686e1f6afde4a50eecccc05668d5e413eafa7c8"
}

**Comment by bossyuansu** [comment]
bc1qwp7pe6xd9s55j98jzqdmnv248fz888pr9xsvt4z6l70mdycq44uqqns3yx

**Comment by eigmax** [comment]
GOAT:  deposit address bc1q8vwmf9lvwkzqwsk5t5leuzq66fxg9sa7zs5uaktzmky9vk3gjw5svk7xcp

**Comment by bossyuansu** [comment]
{
 "owner": "0x09ccd1cb6be49c131c0dd636c95b4e4f5bc549ad",
 "pubkey": "0xeb0881378a4a61f4d27c99460fe4fdf57f9f12423913f037b97f154f481079ada6edaba9d9f219969f5eefdf7af598322f841ad6bb4a1fd85924f32701facb45",
 "signature": "0x350d5782a5df5af8371b5157c4230fcb16afe2edbf775f2634700216eaa72f0e51d458706feb0639519d6556a9ba2e741bc6a03dbb1a50aa71f024ebcff3ea5201",
 "validator": "0x3686e1f6afde4a50eecccc05668d5e413eafa7c8"
}

**Comment by bossyuansu** [comment]
ubuntu@ip-12-0-9-218:/data$ docker run --rm -v /data/goat:/root/.goat ghcr.io/goatnetwork/goat:v0.1.1 modgen locking sign --owner 0x09CCD1cb6bE49c131C0dD636c95B4E4f5bc549aD --eth-chain-id 2345
{
 "owner": "0x09ccd1cb6be49c131c0dd636c95b4e4f5bc549ad",
 "pubkey": "0x9030dc50e99989026ac762131fc9efb03c4ac3ab65cd8201ab025a4f3b6c82b02cb8001723228cf944a7416553b710c9748f48650a717603758799de8dac3a88",
 "signature": "0xe1404f0612e7ef13e27ff9161648137333e72e7088ab5015383dd2b9a8dcfc281ad5bf7fc2c17a94ed4b03f3e09c66598f30dd41597e0bc2c3dcb262c1291e6a00",
 "validator": "0x762e41e7dd3e0708b6a39f1dec870cd89932ecdc"
}

**Comment by bossyuansu** [comment]
bc1qeyf99r2amxpsgrc55z3fvdx2kvulvxv2a88yl2t0r7cmka44nyasnzrkkz
